### PR TITLE
Code cleanups

### PR DESCRIPTION
**Pull request by willpewitt**
This patch is meant to address some issues from https://github.com/rhin123/OpenCiv/issues/57.

### CODE REVIEW

**Comment by rhin123** [comment]
I'm liking what I see so far. I'm looking into getting that build passing on my end, ```You're not authorized to run analysis. No sonar.login or SONAR_TOKEN env variable was set```. I believe it's giving us problems since this is a pull request. Though it shouldn't matter when I merge the PR.

**Comment by willpewitt** [comment]
> I'm liking what I see so far. I'm looking into getting that build passing on my end, `You're not authorized to run analysis. No sonar.login or SONAR_TOKEN env variable was set`. I believe it's giving us problems since this is a pull request. Though it shouldn't matter when I merge the PR.

Awesome, I wanted to get this in a draft state to get some feedback before I continue

**Comment by rhin123** [comment]
> > I'm liking what I see so far. I'm looking into getting that build passing on my end, `You're not authorized to run analysis. No sonar.login or SONAR_TOKEN env variable was set`. I believe it's giving us problems since this is a pull request. Though it shouldn't matter when I merge the PR.
> 
> Awesome, I wanted to get this in a draft state to get some feedback before I continue

As for proper feedback, I like the use using the factory design pattern here. Especially since we have different ```LogTypes``` such as sockets, and general logging. I thought about just creating just one Logger object instance but I think your approach is better.

**Comment by willpewitt** [comment]
I think this is ready for review, I intended to do some other things but the logging stuff touched a lot of LOC.

**Pull request merged**
